version: '3.8'
services:
  dev:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:20
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace:cached
    network_mode: service:redis

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
  redis:
    image: redis-stack
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis-data:/data
volumes:
  redis-data:
